apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-pvc
  namespace: conduit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
