apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smol-kv
  namespace: argocd
spec:
  project: smol-kv
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    targetRevision: main
    path: smol-kv
  destination:
    server: https://kubernetes.default.svc
    namespace: smol-kv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
