apiVersion: v2
name: actions-runner-controller
type: application
version: 0.23.3
dependencies:
  - name: actions-runner-controller
    version: 0.23.3
    repository: https://actions-runner-controller.github.io/actions-runner-controller
