apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: longhorn
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: v1.3.1
    helm:
      releaseName: longhorn
      valueFiles:
      - values.yaml
      parameters:
      - name: ingress.host
        value: lh.mpw.sh
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
