apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: longhorn
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    path: longhorn
    targetRevision: HEAD
    helm:
      releaseName: longhorn
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
