apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ui
  namespace: argocd
spec:
  project: longhorn
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    targetRevision: main
    path: longhorn/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
