apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portier-pvc
  namespace: portier
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
