apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  selector:
    app: redis-server
  type: ClusterIP
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
