apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smol-kv-pvc
  namespace: smol-kv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
