apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: gitea
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    path: gitea
    targetRevision: HEAD
    helm:
      releaseName: gitea
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
