apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: tooling
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: image.tag
        value: v0.18.1
      - name: image.repository
        value: bitnami/sealed-secrets-controller
      - name: namespace
        value: tooling
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
