apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  #Digital Ocean Space
  backupTargetURL: s3://vaexeoul7flnktn2myzn@us-east-1/
  credentialSecret: minio-secret
  pollInterval: 5m0s
