apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: github-actions
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    path: github-actions/controller
    targetRevision: HEAD
    helm:
      releaseName: actions-runner-controller
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - Replace=true
