apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cert-manager
  source:
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    targetRevision: main
    path: cert-manager
    directory:
      recursive: true
    helm:
      releaseName: cert-manager
      parameters:
      - name: cert-manager.installCRDs
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
