apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: tooling
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.9.1
    helm:
      releaseName: cert-manager
      parameters:
      - name: installCRDs
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
