apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubenav
  namespace: argocd
spec:
  project: tooling
  source:
    chart: kubenav
    repoURL: https://kubenav.github.io/helm-repository
    targetRevision: 1.2.0
    helm:
      releaseName: kubenav
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
