apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubenav
  namespace: argocd
spec:
  project: tooling
  source:
    chart: kubenav
    repoURL: https://kubenav.github.io/helm-repository
    repoURL: https://github.com/mpwsh/k3s-arm64.git
    path: kubenav
    targetRevision: main
    helm:
      releaseName: kubenav
      valuesFile:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
